### ISSUE TITLE
Add the ability to specify the SSH port

### ISSUE THREAD

**Issue by skorokithakis** [IlyaSemenov/gitlab-ci-git-push#1]
My SSH (and therefore my git server) runs on a nonstandard port, so it would be nice if I could specify the -p parameter (or other arguments to be passed to SSH) to connect.

**Comment by IlyaSemenov** [comment]
Just use the URL syntax to specify the remote (ssh://git@mypass.host:8022/foo/bar.git:myapp).

I amended the documentation correspondingly.

**Comment by skorokithakis** [comment]
Thank you for the reply. Unfortunately, the problem with that is that I'm not sure which directory one is supposed to use to push to Dokku...

**Comment by IlyaSemenov** [comment]
@skorokithakis I think it's as simple as `git-push ssh://dokku@dokku.me:8022/myapp` - did you try that?

**Comment by skorokithakis** [comment]
Ah, that worked fine, thank you! You might want to add that to the doc

**Comment by skorokithakis** [comment]
Hm no, it didn't work for your image, sorry. `ssh-keyscan` scans the host without the port, and no key is added to `known_hosts`, so connection fails with "Hostkey verification failed.".

**Comment by IlyaSemenov** [comment]
@skorokithakis You are right, I never actually tested it when there was a custom port only. I pushed an updated version which will pass custom port to `ssh-keyscan`. Thanks for persuading.

**Comment by skorokithakis** [comment]
It works perfectly now, thank you.
