### ISSUE TITLE
Working on gitlab.com ?

### ISSUE THREAD

**Issue by kissu** [IlyaSemenov/gitlab-ci-git-push#13]
Hey, I'm not sure if I get it right. Does this package allow me to push to a regular **private** `https://gitlab.com/username/repo` ? :pray:

**Comment by IlyaSemenov** [comment]
Yes, that's the primary purpose of the tool.

**Comment by kissu** [comment]
Because I tried `git-push kissu@gitlab.com:test_weblate master` but it not did worked. :scream_cat: 
Not sure what I messed up here (my un-encrypted SSH key is set).
![image](https://user-images.githubusercontent.com/5133074/80657594-51264480-8a84-11ea-994a-85e6a32ead6e.png)

**Comment by IlyaSemenov** [comment]
Ah, I didn't read the you're asking about gitlab.com specifically. I'll try it in a bit.

**Comment by IlyaSemenov** [comment]
I could not reproduce the problem. I successfully pushed a repo from self-hosted GitLab CI/CD to a test private repo on gitlab.com.

I believe you're using a wrong connection string. It should be `git-push git@gitlab.com:kissu/test_weblate` and not how you put it.
