### ISSUE TITLE
Shallow clone error on Dokku

### ISSUE THREAD

**Issue by iplanwebsites** [IlyaSemenov/gitlab-ci-git-push#14]
Gitlab.com doesn't like big repos. It will attempt a shallow clone by default in the worker.
You need to add these two lines in the` **gitlab-ci**` file to make sure the entire repo is cloned. Dokku wants the full repo.

```
variables:
  GIT_DEPTH: 10000

```

Git error you'll get otherwise sometimes: ! [remote rejected] 1234 -> master (shallow update not allowed)

https://docs.gitlab.com/ee/ci/large_repositories/#git-clean-flags

**Comment by IlyaSemenov** [comment]
Suggestions? Should we document this problem in README? Is there an issue in Dokku github for this problem already?

**Comment by iplanwebsites** [comment]
Modifying the readme should do :)
This issue will now show on google searches, so other people with this problem should quickly find the solution.

**Comment by IlyaSemenov** [comment]
Thank you for the suggestion. Now that I've started to use gitlab-ci-git-push with gitlab.com (not self hosted Gitlab) CI/CD, it has struck me, too. 😃
