### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by chriscrosscutler** [IlyaSemenov/gitlab-ci-git-push#8]
Do you have to use your image? Aka does it need a Docker runner to work or can you just use the script to get it to work?

**Comment by kopax** [comment]
I believe this repo is useless. You can set a `GL_TOKEN` enviromnent variable using a personal access token and do the same with the following `before_script.sh`:


```bash
if [[ -v "GL_TOKEN" || -v "GITLAB_TOKEN" ]]; then
  if [[ "${CI_PROJECT_URL}" =~ (([^/]*/){3}) ]]; then
    mkdir -p $HOME/.config/git
    echo "${BASH_REMATCH[1]/:\/\//://gitlab-ci-token:${GL_TOKEN:-$GITLAB_TOKEN}@}" > $HOME/.config/git/credentials
    git config --global credential.helper store
  fi
fi
```

**Comment by IlyaSemenov** [comment]
@chriscrosscutler:

> Do you have to use your image?

No, you don't. If you don't need it, just don't use it. Simple as that.

> Aka does it need a Docker runner to work or can you just use the script to get it to work?

This is up to you. The suggested use is documented in [How to use](https://github.com/IlyaSemenov/gitlab-ci-git-push#how-to-use) chapter. I never tried to run it without Docker runner as I never needed it. After all it's a very simple image that just fits my needs.

You may just grab the script and use it. It was not made to be reusable outside of Docker runner so YMMV with that. Perhaps it's simpler to create it from scratch, it's just a few lines of code after all.

**Comment by IlyaSemenov** [comment]
@kopax:

> This will give you full access to the repo, only if the project is configured with a `GL_TOKEN`.

Did you even read the project description? Let me cite it for you:

## This GitLab CI runner image allows to deploy a GitLab project to a remote Git repo (useful for Dokku, Heroku, Deis, etc.)

How in the world your token manipulations supposed to "give full access" to e.g. a remote Dokku instance? This is pure nonsense.

This repo is perhaps useless *for your purposes*. Which could be different from other people's purposes.

I am closing the discussion as non-constructive.
