### ISSUE TITLE
Doesn't work on first deploy (when remote has no master)

### ISSUE THREAD

**Issue by cassioalmeidas** [IlyaSemenov/gitlab-ci-git-push#9]
Show following error:

error: unable to push to unqualified destination: master
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'dokku@cassioalmeidas.tk:sota'
ERROR: Job failed: exit code 1

**Comment by IlyaSemenov** [comment]
I like how the problems resolve themselves :)

**Comment by cassioalmeidas** [comment]
I had to do a first deploy through `git push dokku master`

**Comment by JanMikes** [comment]
Hi, i can confirm this issue. 

This command is what is used when using `git-push` command:
```
▶ git push dokku@apps.entry.do:dq-screen-dev HEAD:master --force
Enumerating objects: 400, done.
Counting objects: 100% (400/400), done.
Delta compression using up to 4 threads
Compressing objects: 100% (147/147), done.
Writing objects: 100% (400/400), 90.61 KiB | 30.20 MiB/s, done.
Total 400 (delta 246), reused 394 (delta 242)
remote: Resolving deltas: 100% (246/246), done.
remote: dq-screen-dev currently has a deploy lock in place. Exiting...
To apps.entry.do:dq-screen-dev
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@apps.entry.do:dq-screen-dev'
```
vs
`git push dokku@apps.entry.do:dq-screen-dev ` which works
